building up tests and refactoring around spatial indices

diff --git a/examples/sphere_uniform/Makefile b/examples/sphere_uniform/Makefile
--- a/examples/sphere_uniform/Makefile
+++ b/examples/sphere_uniform/Makefile
@@ -2,18 +2,36 @@
 
 TERRA_FILES = sphere_uniform.t
 
-run: sphere_uniform
-	./sphere_uniform
+run: Sphere_Check sphere_uniform_scan sphere_uniform_bvh
+	./sphere_uniform_scan
+	./sphere_uniform_bvh
 
+# make sure the data to run on is present or present
+# a somewhat comprehensible error to the user otherwise
+Sphere_Check:
+	@if [ -d Spheres ]; then \
+	  echo "found Spheres directory"; \
+	else \
+	  echo "\n  **>> could not find Spheres directory; ASK DEVELOPERS <<**\n"; \
+	  exit 1; \
+	fi
 
-sphere_uniform.o: $(TERRA_FILES)
-	../../bin/gong sphere_uniform.t
+sphere_uniform_scan.o sphere_uniform_scan.h: $(TERRA_FILES)
+	../../bin/gong sphere_uniform.t -suffix=_scan -traversal=scan_scan
 
-sphere_uniform.h: $(TERRA_FILES)
-	../../bin/gong sphere_uniform.t
+sphere_uniform_bvh.o sphere_uniform_bvh.h: $(TERRA_FILES)
+	../../bin/gong sphere_uniform.t -suffix=_bvh -traversal=bvh_bvh
 
-sphere_uniform: sphere_uniform.o sphere_uniform.h main.cpp
-	c++ -o sphere_uniform sphere_uniform.o main.cpp
+sphere_uniform_scan: sphere_uniform_scan.o sphere_uniform_scan.h main.cpp
+	c++ -D USE_SCAN -o sphere_uniform_scan sphere_uniform_scan.o main.cpp
+
+sphere_uniform_bvh: sphere_uniform_bvh.o sphere_uniform_bvh.h main.cpp
+	c++ -D USE_BVH -o sphere_uniform_bvh sphere_uniform_bvh.o main.cpp
 
 clean:
-	rm sphere_uniform.h sphere_uniform.o sphere_uniform
+	rm sphere_uniform_scan.h \
+	   sphere_uniform_scan.o \
+	   sphere_uniform_scan
+	rm sphere_uniform_bvh.h \
+	   sphere_uniform_bvh.o \
+	   sphere_uniform_bvh
